from tests.base_tests.similarity.ruleset import WholeRulesetSimilarityTest
from tests.base_tests.similarity.semantic import SemanticRulesetSimilarityTest
from tests.base_tests.similarity.syntactic import SyntacticRulesetSimilarityTest
