name: Run unit tests on pull request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

        pip install rulekit

    - name: Run tests for the base package
      run: |
        python -m unittest discover ./tests/base_tests

    - name: Install extras dependencies
      run: |
        pip install .[ruleset_factories]

    - name: Run tests for the extras
      run: |
        python -m unittest discover ./tests/extras
